# fly.toml app configuration file generated for gestorinventory-backend on 2025-06-01T07:43:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gestorinventory-backend'
primary_region = 'qro'

[build]

[env]
  NODE_ENV = "production"
<<<<<<< HEAD
  PORT = "5000"

[http_service]
  internal_port = 5000
=======
  PORT = "8080"

[http_service]
  internal_port = 8080
>>>>>>> 6b9ff48 (Actualizar configuración de CORS, ajustar puertos y agregar script de despliegue a Fly.io)
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
